name: causalis
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy>=1.19.0
  - pandas>=1.0.0
  - plotly>=5.0.0
  - scikit-learn
  - catboost
  - pip
  - pip:
    - "-e .[docs]"
  - pydantic